package com.rolling.api.domain.notification.model;

public enum PushNotificationType {
    OPEN_MAT_UPDATED,
    OPEN_MAT_DELETED,
    OPEN_MAT_COMMENT_CREATED,
    OPEN_MAT_COMMENT_REPLY_CREATED,
    SEMINAR_APPLIED,
    SEMINAR_APPLICATION_CANCELED,
    SEMINAR_APPLICATION_CANCELED_BY_HOST,
    SEMINAR_UPDATED,
    SEMINAR_DELETED,
    SEMINAR_CANCELED,
    INQUIRY_ANSWERED,
    COMMUNITY_COMMENT_CREATED,
    FRIEND_REQUEST_RECEIVED,
    TRAINING_LOG_COMMENT_CREATED,
    TRAINING_LOG_COMMENT_REPLY_CREATED,
    TOURNAMENT_FAVORITE_REMINDER
}
