package com.rolling.api.domain.notification.model;

public enum PushNotificationType {
    OPEN_MAT_UPDATED,
    OPEN_MAT_DELETED,
    SEMINAR_APPLIED,
    SEMINAR_APPLICATION_CANCELED,
    SEMINAR_APPLICATION_CANCELED_BY_HOST,
    SEMINAR_UPDATED,
    SEMINAR_DELETED,
    SEMINAR_CANCELED,
    INQUIRY_ANSWERED,
    COMMUNITY_COMMENT_CREATED
}
