# 1. 플러터 앱이 통신할 스프링 백엔드 API 서버
server {
    listen 80;
    listen [::]:80;
    
    # 기본 도메인과 api 서브도메인을 백엔드로 연결
    server_name rolling-app.com api.rolling-app.com; 

    client_max_body_size 20m;

    location / {
        proxy_pass http://api:8080;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;
    }
}

# 2. 나만 볼 수 있는 리액트 관리자 대시보드 서버
server {
    listen 80;
    listen [::]:80;
    
    # 관리자용 서브도메인 (Lightsail DNS에 admin A레코드를 추가해야 합니다!)
    server_name admin.rolling-app.com; 

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        
        # 리액트 라우터 새로고침 에러 방지용
        try_files $uri $uri/ /index.html;

        # '나만 보기' 팝업창 암호 설정
        auth_basic "Admin Dashboard - Restricted Access";
        auth_basic_user_file /etc/nginx/.htpasswd; # 암호 파일 위치
    }
}